base_url = "https://trekar99.github.io"
theme = "kita"

title = "germ√°n's blog"

author = "trekar"

compile_sass = true

#taxonomies = [{ name = "tags", rss = true, paginate_by = 5 }]

build_search_index = true

default_language = "es"

#generate_feeds = true

#feed_filenames = ["atom.xml", "rss.xml"]

[markdown]
highlight_code = true

[extra]
math = true
mermaid = true
comment = true

[[extra.menu]]
name = "About"
url = "$BASE_URL/about"

# [[extra.menu]]
# name = "Projects"
# url = "$BASE_URL/projects"

[[extra.menu]]
name = "Blog"
url = "$BASE_URL/blog"

[[extra.menu]]
name = "Books"
url = "$BASE_URL/books"

[[extra.menu]]
name = "Sports"
url = "$BASE_URL/sports"

[[extra.menu]]
name = "Music"
url = "$BASE_URL/music"

[extra.profile]
name = "trekar"
# bio = "A blog containing my personal rants and findings about software"
avatar_url = "images/mapache.png"

[[extra.profile.social]]
name = "github"
url = "https://github.com/trekar99"

[[extra.profile.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/germanpuertorodriguez/"
